apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: issuance-job
  namespace: '640576971908'
  labels:
    cloud.googleapis.com/location: us-east1
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/cloudsql-instances: rich-store-445612-c6:us-east1:registry-read-us-east1,rich-store-445612-c6:us-east1:registry-write-us-east-1
    run.googleapis.com/vpc-access-connector: registry-vpc
    run.googleapis.com/vpc-access-egress: private-ranges-only
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: rich-store-445612-c6:us-east1:registry-read-us-east1,rich-store-445612-c6:us-east1:registry-write-us-east-1
        run.googleapis.com/vpc-access-connector: registry-vpc
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - name: api-1
            image: us-east1-docker.pkg.dev/rich-store-445612-c6/cloud-run-source-deploy/api:latest
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
            command:
            - "/bin/bash"
            - "-c"
            args:
            - |
              # Make sure script is executable
              chmod +x /code/gc_registry/tasks/issuance-task.sh
              
              # Run the script
              /code/gc_registry/tasks/issuance-task.sh
            env:
            - name: ENVIRONMENT
              value: PROD
            - name: GOOGLE_CLOUD_PROJECT
              value: "640576971908"
            - name: FRONTEND_URL
              value: https://frontend-640576971908.us-east1.run.app
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: FROM_DATE
              value: ""
            - name: TO_DATE
              value: ""
          maxRetries: 1
          timeoutSeconds: '2000'
          serviceAccountName: 640576971908-compute@developer.gserviceaccount.com