apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: issuance-job
  namespace: '640576971908'
  labels:
    cloud.googleapis.com/location: us-east1
  annotations:
    run.googleapis.com/cloudsql-instances: rich-store-445612-c6:us-east1:registry-read-us-east1,rich-store-445612-c6:us-east1:registry-write-us-east-1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: rich-store-445612-c6:us-east1:registry-read-us-east1,rich-store-445612-c6:us-east1:registry-write-us-east-1
    spec:
      taskCount: 1
      template:
        spec:
          containers:
          - name: api-1
            image: us-east1-docker.pkg.dev/rich-store-445612-c6/cloud-run-source-deploy/api:latest
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
            command:
            - "/bin/bash"
            - "-c"
            args:
            - |
              echo "Checking script permissions..."
              ls -la /code/gc_registry/issuance-task.sh
              
              echo "Making script executable..."
              chmod +x /code/gc_registry/issuance-task.sh
              
              echo "Checking Cloud SQL connectivity..."
              ls -la /cloudsql/ || echo "Cloud SQL directory not found"
              
              echo "Running issuance task..."
              /code/gc_registry/issuance-task.sh
            env:
            - name: ENVIRONMENT
              value: PROD
            - name: GOOGLE_CLOUD_PROJECT
              value: "640576971908"
            - name: FRONTEND_URL
              value: https://frontend-640576971908.us-east1.run.app
            - name: PYTHONUNBUFFERED
              value: "1"
          maxRetries: 1
          timeoutSeconds: '600'
          serviceAccountName: 640576971908-compute@developer.gserviceaccount.com