"""gcb_action_source_issuance_id_type

Revision ID: 1949768ee38f
Revises: 5be2b34d1ce9
Create Date: 2024-11-12 11:12:24.709910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1949768ee38f'
down_revision: Union[str, None] = '5be2b34d1ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificateaction', 'action_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('granularcertificateaction', 'source_certificate_issuance_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('granularcertificateaction', 'action_response_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('granularcertificatebundle', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('granularcertificatebundle', 'bundle_quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificatebundle', 'bundle_quantity',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('granularcertificatebundle', 'hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('granularcertificateaction', 'action_response_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('granularcertificateaction', 'source_certificate_issuance_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               postgresql_using="source_certificate_issuance_id::integer",
               existing_nullable=True)
    op.alter_column('granularcertificateaction', 'action_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###