"""add_bundle_percentage_to_action

Revision ID: c3d202419765
Revises: 1949768ee38f
Create Date: 2024-11-24 22:25:49.423713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3d202419765'
down_revision: Union[str, None] = '1949768ee38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificatebundle', 'bundle_id_range_start',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('granularcertificatebundle', 'bundle_id_range_end',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificatebundle', 'bundle_id_range_end',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('granularcertificatebundle', 'bundle_id_range_start',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###