"""missing_ogranisation

Revision ID: f1fe59b637f7
Revises: 1949768ee38f
Create Date: 2024-11-19 12:32:28.731898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fe59b637f7'
down_revision: str | None = 'c3d202419765'
branch_labels: str | Sequence[str] | None = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registry_user', sa.Column('organisation', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registry_user', 'organisation')
    # ### end Alembic commands ###