"""standardise_naming

Revision ID: 9eeb502c46a9
Revises: cd5332cc273e
Create Date: 2024-11-29 16:35:31.825298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eeb502c46a9'
down_revision: Union[str, None] = 'cd5332cc273e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificatebundle', 'bundle_id_range_start', new_column_name='certificate_bundle_id_range_start')
    op.alter_column('granularcertificatebundle', 'bundle_id_range_end', new_column_name='certificate_bundle_id_range_end')

    op.alter_column('granularcertificatebundle', 'certificate_status', new_column_name='certificate_bundle_status')
    op.alter_column('granularcertificateaction', 'certificate_status', new_column_name='certificate_bundle_status')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granularcertificatebundle', 'certificate_bundle_id_range_start', new_column_name='bundle_id_range_start')
    op.alter_column('granularcertificatebundle', 'certificate_bundle_id_range_end', new_column_name='bundle_id_range_end')

    op.alter_column('granularcertificatebundle', 'certificate_bundle_status', new_column_name='certificate_status')
    op.alter_column('granularcertificateaction', 'certificate_bundle_status', new_column_name='certificate_status')

    # ### end Alembic commands ###