"""change_meter_data_id

Revision ID: 700a826fe562
Revises: 9eeb502c46a9
Create Date: 2024-12-19 18:00:29.371327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '700a826fe562'
down_revision: Union[str, None] = '9eeb502c46a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='device', column_name='meter_data_id', new_column_name='local_device_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='device', column_name='local_device_identifier', new_column_name='meter_data_id')
    # ### end Alembic commands ###