"""add_whitelist_link_table

Revision ID: 1726695ba27a
Revises: 89c567c7f2b2
Create Date: 2025-01-12 18:21:29.190609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1726695ba27a'
down_revision: Union[str, None] = '89c567c7f2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountwhitelistlink',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=False),
    sa.Column('target_account_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('account', 'account_whitelist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accountwhitelistlink')
    op.add_column('account', sa.Column('account_whitelist', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###
