"""explicit_user_email_auth

Revision ID: fad1cb871574
Revises: 1726695ba27a
Create Date: 2025-01-24 10:37:38.458441

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fad1cb871574'
down_revision: Union[str, None] = '1726695ba27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registry_user', column_name="primary_contact", new_column_name="email", nullable=False)
    op.alter_column('tokenrecords', column_name="user_name", new_column_name="email", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokenrecords', column_name="email", new_column_name="user_name", nullable=False)
    op.alter_column('registry_user', column_name="email", new_column_name="primary_contact", nullable=True)
    # ### end Alembic commands ###