"""remove_account_ids_from_user

Revision ID: fa7d18bc5381
Revises: fad1cb871574
Create Date: 2025-01-24 16:38:21.430452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa7d18bc5381"
down_revision: Union[str, None] = "fad1cb871574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registry_user", "account_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "registry_user",
        sa.Column("account_ids", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
