"""device_enums

Revision ID: 1919bd85511d
Revises: fa7d18bc5381
Create Date: 2025-02-26 14:09:07.169444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1919bd85511d'
down_revision: Union[str, None] = 'fa7d18bc5381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    energy_source_enum = sa.Enum('solar_pv', 'wind', 'hydro', 'biomass', 'nuclear', 'electrolysis', 'geothermal', 'battery_storage', 'chp', 'other', name='energysourcetype')
    energy_source_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('device', 'energy_source',
               existing_type=sa.VARCHAR(),
               type_=energy_source_enum,
               existing_nullable=False,
               postgresql_using="energy_source::energysourcetype")
    technology_type_enum = sa.Enum('solar_pv', 'wind_turbine', 'hydro', 'battery_storage', 'other_storage', 'chp', 'other', name='devicetechnologytype')
    technology_type_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('device', 'technology_type',
               existing_type=sa.VARCHAR(),
               type_=technology_type_enum,
               existing_nullable=False,
               postgresql_using="technology_type::devicetechnologytype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'technology_type',
               existing_type=sa.Enum('solar_pv', 'wind_turbine', 'hydro', 'battery_storage', 'other_storage', 'chp', 'other', name='devicetechnologytype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('device', 'energy_source',
               existing_type=sa.Enum('solar_pv', 'wind', 'hydro', 'biomass', 'nuclear', 'electrolysis', 'geothermal', 'battery_storage', 'chp', 'other', name='energysourcetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###