"""additional_refactor_to_storage

Revision ID: c0b3b491de92
Revises: ff84d5699c72
Create Date: 2025-03-23 16:37:07.075424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0b3b491de92'
down_revision: Union[str, None] = 'ff84d5699c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocatedstoragerecord', sa.Column('sdr_proportion', sa.Float(), nullable=False))
    op.add_column('allocatedstoragerecord', sa.Column('scr_allocation_methodology', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('allocatedstoragerecord', sa.Column('efficiency_factor_methodology', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('allocatedstoragerecord', sa.Column('efficiency_factor_interval_start', sa.DateTime(), nullable=False))
    op.add_column('allocatedstoragerecord', sa.Column('efficiency_factor_interval_end', sa.DateTime(), nullable=False))
    op.add_column('allocatedstoragerecord', sa.Column('storage_efficiency_factor', sa.Float(), nullable=False))
    op.alter_column('allocatedstoragerecord', 'gc_allocation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('allocatedstoragerecord', 'sdgc_allocation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('allocatedstoragerecord_account_id_fkey', 'allocatedstoragerecord', type_='foreignkey')
    op.drop_column('allocatedstoragerecord', 'account_id')
    op.alter_column('registry_user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'PRODUCTION_USER', 'TRADING_USER', 'AUDIT_USER', name='userrolestype'),
               type_=postgresql.ENUM('ADMIN', 'PRODUCTION_USER', 'TRADING_USER', 'AUDIT_USER', 'STORAGE_VALIDATOR', name='userrolestype'),
               existing_nullable=False)
    op.add_column('storagerecord', sa.Column('validator_id', sa.Integer(), nullable=True))
    op.alter_column('storagerecord', 'flow_energy_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('storagerecord_account_id_fkey', 'storagerecord', type_='foreignkey')
    op.drop_column('storagerecord', 'gc_issuance_id')
    op.drop_column('storagerecord', 'scr_allocation_methodology')
    op.drop_column('storagerecord', 'efficiency_factor_interval_start')
    op.drop_column('storagerecord', 'efficiency_factor_methodology')
    op.drop_column('storagerecord', 'certificate_bundle_id_range_end')
    op.drop_column('storagerecord', 'certificate_bundle_id_range_start')
    op.drop_column('storagerecord', 'account_id')
    op.drop_column('storagerecord', 'efficiency_factor_interval_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storagerecord', sa.Column('efficiency_factor_interval_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('storagerecord', sa.Column('certificate_bundle_id_range_start', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('certificate_bundle_id_range_end', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('efficiency_factor_methodology', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('efficiency_factor_interval_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('scr_allocation_methodology', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('gc_issuance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('storagerecord_account_id_fkey', 'storagerecord', 'account', ['account_id'], ['id'])
    op.alter_column('storagerecord', 'flow_energy_source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('storagerecord', 'validator_id')
    op.alter_column('registry_user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'PRODUCTION_USER', 'TRADING_USER', 'AUDIT_USER', 'STORAGE_VALIDATOR', name='userrolestype'),
               type_=postgresql.ENUM('ADMIN', 'PRODUCTION_USER', 'TRADING_USER', 'AUDIT_USER', name='userrolestype'),
               existing_nullable=False)
    op.add_column('allocatedstoragerecord', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('allocatedstoragerecord_account_id_fkey', 'allocatedstoragerecord', 'account', ['account_id'], ['id'])
    op.alter_column('allocatedstoragerecord', 'sdgc_allocation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('allocatedstoragerecord', 'gc_allocation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('allocatedstoragerecord', 'storage_efficiency_factor')
    op.drop_column('allocatedstoragerecord', 'efficiency_factor_interval_end')
    op.drop_column('allocatedstoragerecord', 'efficiency_factor_interval_start')
    op.drop_column('allocatedstoragerecord', 'efficiency_factor_methodology')
    op.drop_column('allocatedstoragerecord', 'scr_allocation_methodology')
    op.drop_column('allocatedstoragerecord', 'sdr_proportion')
    # ### end Alembic commands ###