"""meter_data_id

Revision ID: 9b6ad74b1a31
Revises: 2cb0ec2de122
Create Date: 2024-10-15 13:53:55.040486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6ad74b1a31'
down_revision: str | None = '6409ce42f7e7'
branch_labels: str | Sequence[str] | None = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('meter_data_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'meter_data_id')
    # ### end Alembic commands ###