"""enforce_local_indentifier_unique

Revision ID: 772bff438724
Revises: 800213efcf78
Create Date: 2025-07-09 13:28:18.266279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772bff438724'
down_revision: Union[str, None] = '800213efcf78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TYPE userrolestype ADD VALUE IF NOT EXISTS 'STORAGE_VALIDATOR'")

    op.create_index(op.f('ix_device_local_device_identifier'), 'device', ['local_device_identifier'], unique=True)

    op.drop_column('storageaction', 'storage_energy_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storageaction', sa.Column('storage_energy_source', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_index(op.f('ix_device_local_device_identifier'), table_name='device')

    new_enum = sa.Enum(
        'ADMIN',
        'PRODUCTION_USER',
        'TRADING_USER',
        'AUDIT_USER',
        name='userrolestype_new'
    )
    new_enum.create(op.get_bind())

    existing_enum = sa.Enum(
        'ADMIN',
        'PRODUCTION_USER',
        'TRADING_USER',
        'AUDIT_USER',
        'STORAGE_VALIDATOR',
        name='userrolestype_existing'
    )
    existing_enum.create(op.get_bind())
    op.execute("ALTER TYPE userrolestype RENAME TO userrolestype_old")
    op.execute("ALTER TYPE userrolestype_new RENAME TO userrolestype")

    # now make sure that the new enum type is used in the user table
    op.execute(
        "ALTER TABLE registry_user ALTER COLUMN role TYPE userrolestype USING role::text::userrolestype"
    )


    # drop the old enum type
    op.execute("DROP TYPE userrolestype_old")

    # ### end Alembic commands ###