"""change_is_storage_to_bool

Revision ID: 1f33f8a1e289
Revises: 772bff438724
Create Date: 2025-07-10 13:25:50.755090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f33f8a1e289'
down_revision: Union[str, None] = '772bff438724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert integer to boolean with explicit casting
    op.execute("ALTER TABLE granularcertificatebundle ALTER COLUMN is_storage TYPE BOOLEAN USING is_storage::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert boolean back to integer with explicit casting
    op.execute("ALTER TABLE granularcertificatebundle ALTER COLUMN is_storage TYPE INTEGER USING is_storage::integer")
    # ### end Alembic commands ###