"""refactor_device_capacity

Revision ID: 2f7dda77c60f
Revises: ad88c7657a17
Create Date: 2025-07-30 11:42:48.197948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7dda77c60f'
down_revision: Union[str, None] = 'ad88c7657a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('power_mw', sa.Float(), nullable=False))
    op.add_column('device', sa.Column('energy_mwh', sa.Float(), nullable=True))
    op.drop_column('device', 'capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('capacity', sa.Float(), autoincrement=False, nullable=False))
    op.drop_column('device', 'energy_mwh')
    op.drop_column('device', 'power_mw')
    # ### end Alembic commands ###