"""add_account_whitelist

Revision ID: 9c5b09eea511
Revises: 5d4f91b04de4
Create Date: 2024-11-27 19:55:22.295789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c5b09eea511'
down_revision: Union[str, None] = '5d4f91b04de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_whitelist', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'account_whitelist')
    # ### end Alembic commands ###