"""add_storage_constraint

Revision ID: 82a3317c274a
Revises: 1832fcb8a0de
Create Date: 2024-09-22 13:05:24.705968

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82a3317c274a"
down_revision: Union[str, None] = "1832fcb8a0de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "storagechargerecord_sdr_allocation_id_fkey",
        "storagechargerecord",
        "storagedischargerecord",
        ["sdr_allocation_id"],
        ["sdr_allocation_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "storagechargerecord_sdr_allocation_id_fkey",
        "storagechargerecord",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
