"""remove_storage_energy_source

Revision ID: 800213efcf78
Revises: c0b3b491de92
Create Date: 2025-03-25 15:09:25.941903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800213efcf78'
down_revision: Union[str, None] = 'c0b3b491de92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storagerecord', sa.Column('is_charging', sa.Boolean(), nullable=False))
    op.drop_column('storagerecord', 'flow_type')
    op.drop_column('storagerecord', 'flow_energy_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storagerecord', sa.Column('flow_energy_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('storagerecord', sa.Column('flow_type', postgresql.ENUM('CHARGING', 'DISCHARGING', name='flowtype'), autoincrement=False, nullable=False))
    op.drop_column('storagerecord', 'is_charging')
    # ### end Alembic commands ###