"""refactor_storage_records

Revision ID: ff84d5699c72
Revises: 1919bd85511d
Create Date: 2025-03-23 14:10:06.905683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'ff84d5699c72'
down_revision: Union[str, None] = '1919bd85511d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storagerecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('flow_type', sa.Enum('CHARGING', 'DISCHARGING', name='flowtype'), nullable=False),
    sa.Column('flow_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('flow_end_datetime', sa.DateTime(), nullable=False),
    sa.Column('flow_energy', sa.Float(), nullable=False),
    sa.Column('flow_energy_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gc_issuance_id', sa.Integer(), nullable=True),
    sa.Column('certificate_bundle_id_range_start', sa.Integer(), nullable=True),
    sa.Column('certificate_bundle_id_range_end', sa.Integer(), nullable=True),
    sa.Column('scr_allocation_methodology', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('efficiency_factor_methodology', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('efficiency_factor_interval_start', sa.DateTime(), nullable=True),
    sa.Column('efficiency_factor_interval_end', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocatedstoragerecord',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('scr_allocation_id', sa.Integer(), nullable=False),
    sa.Column('sdr_allocation_id', sa.Integer(), nullable=False),
    sa.Column('gc_allocation_id', sa.Integer(), nullable=False),
    sa.Column('sdgc_allocation_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['gc_allocation_id'], ['granularcertificatebundle.id'], ),
    sa.ForeignKeyConstraint(['scr_allocation_id'], ['storagerecord.id'], ),
    sa.ForeignKeyConstraint(['sdgc_allocation_id'], ['granularcertificatebundle.id'], ),
    sa.ForeignKeyConstraint(['sdr_allocation_id'], ['storagerecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('granularcertificatebundle_sdr_allocation_id_fkey', 'granularcertificatebundle', type_='foreignkey')
    op.drop_column('granularcertificatebundle', 'sdr_allocation_id')
    op.drop_constraint('storagechargerecord_sdr_allocation_id_fkey', 'storagechargerecord', type_='foreignkey')
    op.drop_table('storagedischargerecord')
    op.drop_table('storagechargerecord')
    op.drop_constraint('accountwhitelistlink_source_account_id_fkey', 'accountwhitelistlink', type_='foreignkey')
    op.drop_constraint('accountwhitelistlink_target_account_id_fkey', 'accountwhitelistlink', type_='foreignkey')
    op.add_column('granularcertificatebundle', sa.Column('allocated_storage_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'granularcertificatebundle', 'allocatedstoragerecord', ['allocated_storage_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granularcertificatebundle', sa.Column('sdr_allocation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'granularcertificatebundle', type_='foreignkey')
    op.create_foreign_key('granularcertificatebundle_sdr_allocation_id_fkey', 'granularcertificatebundle', 'storagedischargerecord', ['sdr_allocation_id'], ['sdr_allocation_id'])
    op.drop_column('granularcertificatebundle', 'allocated_storage_record_id')
    op.create_foreign_key('accountwhitelistlink_target_account_id_fkey', 'accountwhitelistlink', 'account', ['target_account_id'], ['id'])
    op.create_foreign_key('accountwhitelistlink_source_account_id_fkey', 'accountwhitelistlink', 'account', ['source_account_id'], ['id'])
    op.create_table('storagechargerecord',
    sa.Column('charging_start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('charging_end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('charging_energy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charging_energy_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gc_issuance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_bundle_id_range_start', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_bundle_id_range_end', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scr_geographic_matching_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sdr_allocation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scr_allocation_id', sa.INTEGER(), server_default=sa.text("nextval('storagechargerecord_scr_allocation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='storagechargerecord_account_id_fkey'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='storagechargerecord_device_id_fkey'),
    sa.ForeignKeyConstraint(['sdr_allocation_id'], ['storagedischargerecord.sdr_allocation_id'], name='storagechargerecord_sdr_allocation_id_fkey'),
    sa.PrimaryKeyConstraint('scr_allocation_id', name='storagechargerecord_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('storagedischargerecord',
    sa.Column('discharging_start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('discharging_end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('discharge_energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('charging_energy_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scr_allocation_methodology', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('efficiency_factor_methodology', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('efficiency_factor_interval_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('efficiency_factor_interval_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sdr_allocation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scr_allocation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='storagedischargerecord_account_id_fkey'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='storagedischargerecord_device_id_fkey'),
    sa.ForeignKeyConstraint(['scr_allocation_id'], ['storagechargerecord.scr_allocation_id'], name='storagedischargerecord_scr_allocation_id_fkey'),
    sa.PrimaryKeyConstraint('sdr_allocation_id', name='storagedischargerecord_pkey')
    )
    op.drop_table('storagerecord')
    op.drop_table('allocatedstoragerecord')
    # ### end Alembic commands ###